language: rust
sudo: false
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
install:
  - pip install --user cram
script:
  - cargo test --verbose
  - $HOME/.local/bin/cram tests/cli
